apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: visputesagarg/frontend-to-do-app:v1
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            valueFrom:
              secretKeyRef:
                name: backend-sec
                key: backend_url
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  namespace: three-tier
  name: backend-sec
type: Opaque
data:
  backend_url: aHR0cDovL2FwaS50aHJlZS10aWVyLnN2Yy5jbHVzdGVyLmxvY2Fs
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: NodePort
  selector:
    role: frontend
